[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Key = "Path", Value = "/*"}

[[headers]]
  for = "/*"
  [headers.values]
    "X-Frame-Options" = "DENY"
    "X-XSS-Protection" = "1; mode=block"